### ISSUE TITLE
somthing wrong when i run the code

### ISSUE THREAD

**Issue by heylary** [Adddedtiya/SimpleYoloAug#1]
helo,i try your code but there seems somthing wrong,could your please help me? Thanks!!
When i run the code ,it always show:
(yolov5) D:\WorkData\DeepLearning\yolov5\SimpleYoloAug>python simple_augment.py --indir train/images/ --outdir /gen_images/ --gen 2
_Total Image Anotation Pair : 0
Y/N : y
0it [00:00, ?it/s]_
my dir is correct,and i don't know where is wrong.
H

**Comment by Adddedtiya** [comment]
is your images jpeg/jpg ? also make sure that the annotations is in the same folder as the images and have the same name 

so it would be something like this: 

1.jpg  1.txt

**Comment by heylary** [comment]
> is your images jpeg/jpg ? also make sure that the annotations is in the same folder as the images and have the same name
> 
> so it would be something like this:
> 
> 1.jpg 1.txt

yes，sincerely thanks for your help！
